In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../Datasets/Food_Inspections.csv")

In [4]:
df.head(3)

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,2352760,PLAZA FOOD AND LIQUOR,PLAZA FOOD AND LIQUOR,2689757.0,Grocery Store,Risk 3 (Low),3455-3459 S OGDEN AVE,CHICAGO,IL,60623.0,12/04/2019,License Re-Inspection,Pass,NaN,NaN,NaN,NaN
1,2312358,"PACINO'S RC, LLC",PACINOS,2683668.0,Restaurant,Risk 3 (Low),1010 S DELANO CT,CHICAGO,IL,60605.0,09/16/2019,License Re-Inspection,Pass,NaN,NaN,NaN,NaN
2,2293464,COURAGEOUS BAKERY,COURAGEOUS BAKERY,2349251.0,Mobile Food Dispenser,Risk 3 (Low),108 W PARK,ELMHURST,IL,60126.0,06/13/2019,Canvass,Out of Business,NaN,NaN,NaN,NaN

In [5]:
df[df.Location.notnull()]

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
1800,2401254,"GOLDEN HOOK FISH, CHICKEN","GOLDEN HOOK FISH, CHICKEN",2069859.0,Restaurant,Risk 2 (Medium),5215 W CHICAGO AVE BLDG E2,CHICAGO,IL,60651.0,09/16/2020,Complaint,Pass w/ Conditions,5. PROCEDURES FOR RESPONDING TO VOMITING AND D...,41.894815,-87.756302,"(41.89481469929343, -87.75630215901684)"
2373,2304200,GORILLA SUSHI,GORILLA SUSHI,2398633.0,Restaurant,Risk 1 (High),4945 N MILWAUKEE AVE UNIT 2,CHICAGO,IL,60630.0,08/06/2019,Canvass,Fail,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.970759,-87.763147,"(41.970758727750066, -87.76314717614609)"
4963,2320485,CHILDREN'S LEARNING PLACE,CHILDREN'S LEARNING PLACE,2215986.0,Children's Services Facility,Risk 1 (High),1669 N MILWAUKEE AVE .,CHICAGO,IL,60647.0,10/25/2019,License,Pass w/ Conditions,"48. WAREWASHING FACILITIES: INSTALLED, MAINTAI...",41.911812,-87.679456,"(41.91181218267389, -87.67945575173174)"
6511,2301155,FEDERALES,FEDERALES,2671495.0,Restaurant,Risk 2 (Medium),150 E RANDOLPH ST FL 11TH,CHICAGO,IL,60601.0,07/16/2019,License,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.884628,-87.622613,"(41.88462844513973, -87.62261269904712)"
6844,491234,NOTRE DAME AMONG US,NOTRE DAME AMONG US,2074572.0,Grocery Store,Risk 3 (Low),1943 W HOWARD ST BLDG FLOOR,CHICAGO,IL,60626.0,01/18/2011,License,Fail,"9. WATER SOURCE: SAFE, HOT & COLD UNDER CITY P...",42.019329,-87.679435,"(42.019329138296634, -87.67943535082605)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210403,1234342,Catering by Roxana,Catering by Roxana,2177734.0,Shared Kitchen User (Long Term),Risk 1 (High),551 W North AVE STE 308,CHICAGO,IL,60610.0,07/26/2012,License,Pass,NaN,41.910934,-87.643033,"(41.91093416444757, -87.6430328674124)"
211379,2369662,SALERNO'S,SALERNO'S,2670354.0,Restaurant,Risk 1 (High),1201 W GRAND AVE FL 1,CHICAGO,IL,60642.0,04/23/2020,Canvass,Pass,41. WIPING CLOTHS: PROPERLY USED & STORED - Co...,41.890970,-87.657466,"(41.89096990066963, -87.65746645551516)"
211518,1234790,CHESHIRE CAT CONFECTIONARY LLC,CHESHIRE CAT CONFECTIONARY LLC,2183640.0,Shared Kitchen User (Long Term),Risk 2 (Medium),235 W EUGENIE UNIT M2,CHICAGO,IL,60614.0,08/21/2012,License,Pass,NaN,41.912750,-87.636234,"(41.912750161826274, -87.63623374961809)"
212020,1199581,JIMMY JOHN'S,JIMMY JOHN'S,1823750.0,Restaurant,Risk 1 (High),200 N JEFFERSON STE1,CHICAGO,IL,60661.0,10/27/2014,Canvass,Pass,38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS...,41.885758,-87.642922,"(41.88575801779178, -87.64292191698021)"
212097,2268420,POPEYES CHICKEN,POPEYES CHICKEN,2646821.0,Restaurant,Risk 1 (High),156 N WABASH AVE FL 1,CHICAGO,IL,60601.0,02/22/2019,License,Not Ready,NaN,41.884715,-87.626400,"(41.88471487688737, -87.62640013225639)"